### ISSUE TITLE
[Fabric] Crash on Server

### ISSUE THREAD

**Issue by MSandro** [PssbleTrngle/Skygrid#50]
**Describe the bug**
can not start my server with this mod

**To Reproduce**
1. install newest Version of SkyGrid on a Fabric 1.18.2 Server (Loader 0.14.8, API 0.58.0)
2. start the server
3. latest.log: https://gist.github.com/MSandro/06a0aa7c58e088da67ea9b9661ceae5d

**Expected behavior**
not crashing!

**Version**
Modloader: Fabric
Modloader Version: 0.14.8
Mod Version: 3.0.7

**Comment by PssbleTrngle** [comment]
Sounds like the mixin is trying to load a class that should only be loaded client-side.
If that's the case it should be an easy fix

**Comment by PssbleTrngle** [comment]
Ok no, seems it's a flaw in my code design

**Comment by CarbyDood** [comment]
Any update on this? im having the same exact issue. Any fix, even a temp one to do on my end, would be fine

**Comment by PssbleTrngle** [comment]
Sorry, I tried to fix it but couldn't solve the problem, I'll try again tomorrow

**Comment by PssbleTrngle** [comment]
Should hopefully be fixed in version 3.0.8

**Comment by CarbyDood** [comment]
Seems that fixed the issue with mixin, but the server unfortunately still crashes, this time it seems to be an issue with "net/minecraft/class_5317", which according to https://maven.fabricmc.net/docs/yarn-22w13oneblockatatime+build.1/net/minecraft/client/world/GeneratorType.html is also client only? sorry if this is causing you inconvience i just really need this mod to work on a server, heh...

here's the pastebin for the full crash: https://pastebin.com/VFGwzLqb

**Comment by PssbleTrngle** [comment]
Which fabric version are you on?

**Comment by PssbleTrngle** [comment]
Ok I found the issue

**Comment by CarbyDood** [comment]
i know ya found the issue but if it helps anything, my fabric version is 0.14.8 (1 version below the current major release). Fabric API is 0.58.0+, and fabric-language-kotlin is 1.8.2 with kotlin 1.7.10. MC version is 1.18.2

**Comment by PssbleTrngle** [comment]
Can you try with the new version I released? I think I fixed it

**Comment by CarbyDood** [comment]
Yep, that works! thank you! if i run into any other issues i'll open a new issue, but for now i think this one's fixed

**Comment by PssbleTrngle** [comment]
Nice 🎉
